### ISSUE TITLE
Handling of 5xx error in google_api_helper

### ISSUE THREAD

**Issue by ghelobytes** [jonparrott/Ferris2#4]
The documentation says that: "Will retry if an HttpError in the 5xx range is raise, but will fail if the error is in the 4xx range." But I don't see anywhere in this policy (function) how the 5xx will be retried if it is encountered. Am I missing something?
```
def apiclient_retry_policy(exception):
    if not isinstance(exception, errors.HttpError):
        return False

    try:
        error = json.loads(exception.content)
        error = error.get('error', error)
        code = error.get('code')
        reason = error.get('errors', [{}])[0].get('reason')
        if code == 403 and reason in ('rateLimitExceeded', 'userRateLimitExceeded'):
            logging.info("Rate limit exceeded, retrying...")
            return True
        elif code == 403 and reason in ('dailyLimitExceeded',):
            logging.error("Uh oh- daily quota limit exceeded!")
            return False
        elif code == 403:
            logging.info("I think the rate limit was exceeded (reason was %s), so retrying..." % reason)
            return True
        else:
            logging.info("Non-rate limit API error %s raised" % error.get('message'))

    except ValueError:
        logging.error("Failed to parse json from exception: %s" % exception.content)

    return False
```

**Comment by jonparrott** [comment]
You're absolutely right, the policy does not automatically retry on 5xx, and does indeed retry when a 403 is given. The documentation should be updated and I suppose the policy should be augmented to handle 500.

**Comment by ghelobytes** [comment]
Thanks for confirming that @jonparrott . I was suspecting its because the 500 aren't being handled that's why it is not retrying in my case. Turns out DeadlineExceeded error are being thrown because the API call is taking more than 5 seconds. Looks like this policy isn't also handling that because of:
```
    if not isinstance(exception, errors.HttpError):
        return False
```
I guess I'm gonna have to customize the policy just a little bit.

Thanks again.
